config/routes.rb
Rails.application.routes.draw do
  get "payment/index"
  post "payment/purchase"
  get "payment/purchased"
  root 'about#index'
  get "mypage/applying"
  get "mypage/applied"
  get "about/index"
  match '/about', to:'about#index', via:'get'
  # match '/signin',  to: 'sessions#new',         via: 'get'
  # match '/signout', to: 'sessions#destroy',     via: 'delete'

  devise_for :users, :controllers => {
  :registrations => "users/registrations",
  :omniauth_callbacks => "users/omniauth_callbacks"
}

  resources :users do
    member do
      get :applies, :reviewed, :reviewing
    end
  end


  resources :jobs

  resources :applies do
    member do
      get :approve
    end
  end

  resources :messages

  resources :mypages

  resources :reviews

  resources :tags

end

app/models/apply.rb
class Apply < ActiveRecord::Base
  belongs_to :user
  belongs_to :job
  has_many :message
  has_many :jobs
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  before_action :set_apply, only: [:show, :edit, :update, :destroy, :approve]

  # GET /applies
  # GET /applies.json
  def index
    @jobs = current_user.jobs
  end

  # GET /applies/1
  # GET /applies/1.json
  def show
  end

  # GET /applies/new
  def new
    @apply = Apply.new
  end

  # GET /applies/1/edit
  def edit
  end

  # POST /applies
  # POST /applies.json
  def create
    @job = Job.find(params[:job_id])
    current_user.apply!(@job)
    redirect_to @job
  end

  def approve
    # @applyのstatusを1にする
    @apply.status = 1
    @apply.save
    # saveする
    # redirectする
    redirect_to  @apply
  end


  # PATCH/PUT /applies/1
  # PATCH/PUT /applies/1.json
  def update
    respond_to do |format|
      if @apply.update(apply_params)
        format.html { redirect_to @apply, notice: 'Apply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @apply.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /applies/1
  # DELETE /applies/1.json
  def destroy
    @job = Apply.find(params[:id]).job
    current_user.unapply!(@job)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apply
      @apply = Apply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apply_params
      params.require(:apply).permit(:user_id, :job_id, :status)
    end
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/views/applies/_form.html.erb
<%= form_for(@apply) do |f| %>
  <% if @apply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apply.errors.count, "error") %> prohibited this apply from being saved:</h2>

      <ul>
      <% @apply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :job_id %><br>
    <%= f.number_field :job_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applies/edit.html.erb
<h1>Editing apply</h1>

<%= render 'form' %>

<%= link_to 'Show', @apply %> |
<%= link_to 'Back', applies_path %>

app/views/applies/index.html.erb
<div class="mk">
<% @jobs.each do |job|%>
<% job.applies.each do |apply| %>
<table class="table table-hover">

<tbody>

<td><%= job.title %></td>

<td>
  <%= apply.user.name %>
</td>

<td>
  <% if apply.status == 1 %>
      <%= '承認済み' %>
  <% else %>
      <%= link_to '承認する', approve_apply_path(id: apply.id) %>
  <% end %>
</td>

<td id="WP_checkoutBox"><%= link_to 'お支払い', payment_index_path , method: :get %></td>

</tbody>

</table>


  <% end %>
<% end %>

</div>

app/views/applies/new.html.erb
<h1>New apply</h1>

<%= render 'form' %>

<%= link_to 'Back', applies_path %>

app/views/applies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @apply.user.name %>
</p>

<p>
  <strong>Job:</strong>
  <%= @apply.job.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @apply.status %>
</p>



<%= link_to 'Edit', edit_apply_path(@apply) %> |
<%= link_to 'Back', applies_path %>