config/routes.rb
Rails.application.routes.draw do
  get "payment/index"
  post "payment/purchase"
  get "payment/purchased"
  root 'about#index'
  get "mypage/applying"
  get "mypage/applied"
  get "about/index"
  match '/about', to:'about#index', via:'get'
  # match '/signin',  to: 'sessions#new',         via: 'get'
  # match '/signout', to: 'sessions#destroy',     via: 'delete'

  devise_for :users, :controllers => {
  :registrations => "users/registrations",
  :omniauth_callbacks => "users/omniauth_callbacks"
}

  resources :users do
    member do
      get :applies, :reviewed, :reviewing
    end
  end


  resources :jobs

  resources :applies do
    member do
      get :approve
    end
  end

  resources :messages

  resources :mypages

  resources :reviews

  resources :tags

end

app/models/job.rb
class Job < ActiveRecord::Base
  acts_as_taggable # acts_as_taggable_on :tags のエイリアス
  acts_as_taggable_on :skills, :interests
  belongs_to :user
  has_many :applies
  default_scope -> { order('created_at DESC') }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    @jobs = Job.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @tags = @job.tags
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:status, :fee, :title, :introduction, :deadline, :place, :name, :tag_list)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="row mm">
<div class="span6 offset3">

<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div> -->
  <div class="field">
    <%= f.label :金額 %><br>
    <%= f.text_field :fee %>
  </div>
<!--   <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
  <div class="field">
    <%= f.label :イベント名 %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :作業内容 %><br>
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.label :いつ？ %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :どこで？ %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :仕事のタグ %><br>
    <%= f.text_field :tag_list, placeholder: "タグ" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div><!-- /.span6 offset3 -->
</div><!-- /.row -->

app/views/jobs/_job.html.erb
<% if(job.title) %>

  <tbody>
      <tr>
        <td><%= job.status %></td>
        <td><%= job.fee %></td>
        <td><%= job.user_id %></td>
        <td><%= job.title %></td>
        <td><%= job.introduction %></td>
        <td><%= job.deadline %></td>
        <td><%= job.place %></td>
     </tr>
  </tbody>
</table>

<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div class="jobMt">

<h2>仕事一覧</h2>

<div class="col-xs-6 col-sm-8">

<table class="table table-hover .table-bordered">
  <thead>
    <tr>
      <th>報酬額</th>
      <th>依頼者名</th>
      <th>イベント名</th>
      <th>作業内容</th>
      <th>いつ？</th>
      <th>どこで？</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.fee %></td>
        <td><%= link_to job.user.name, user_path(job.user) %></td>
        <td><%= job.title %></td>
        <td><%= job.introduction %></td>
        <td><%= job.deadline %></td>
        <td><%= job.place %></td>
        <td class="btn btnMore btn-sm"><%= link_to 'もっと見る', job %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

<%= will_paginate @jobs %>

app/views/jobs/new.html.erb
<div>
<h1>イベントを投稿</h1>

<%= render 'form' %>

<span class=" btn btn-success BackD"><%= link_to '戻る', jobs_path %></span>

</div>

app/views/jobs/show.html.erb
<div class="PT100">
<p id="notice"><%= notice %></p>



<table class="table table-hover">
  <thead>
    <tr>
        <td>報酬</td>
        <td>依頼者名</td>
        <td>イベント名</td>
        <td>作業内容</td>
        <td>いつ？</td>
        <td>どこで？</td>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @job.fee %></td>
        <td><%= @job.user.name %></td>
        <td><%= @job.title %></td>
        <td><%= @job.introduction %></td>
        <td><%= @job.deadline %></td>
        <td><%= @job.place %></td>
      </tr>
  </tbody>
</table>

<div>
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
<div class="original-tag"><%= link_to tag.name, tag_path(tag.id) %>
</div>
<% end %>
<div class="btn btn-success applybtn">
<% if current_user.apply?(@job) %>
    <%= '申請中' %>
<% else %>
    <%= link_to '申請する', applies_path(job_id: @job.id), method: :post %>
<% end %>
</div>

<div class="btn btn-success applybtn">
<%= link_to '戻る', jobs_path %>
</div>

</div>
</div>