config/routes.rb
Rails.application.routes.draw do
  get "payment/index"
  post "payment/purchase"
  get "payment/purchased"
  root 'about#index'
  get "mypage/applying"
  get "mypage/applied"
  get "about/index"
  match '/about', to:'about#index', via:'get'
  # match '/signin',  to: 'sessions#new',         via: 'get'
  # match '/signout', to: 'sessions#destroy',     via: 'delete'

  devise_for :users, :controllers => {
  :registrations => "users/registrations",
  :omniauth_callbacks => "users/omniauth_callbacks"
}

  resources :users do
    member do
      get :applies, :reviewed, :reviewing
    end
  end


  resources :jobs

  resources :applies do
    member do
      get :approve
    end
  end

  resources :messages

  resources :mypages

  resources :reviews

  resources :tags

end

app/models/mypage.rb
class Mypage < ActiveRecord::Base
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :set_mypage, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
  end

  def show
    respond_with(@mypage)
  end

  def new
    @mypage = Mypage.new
    respond_with(@mypage)
  end

  def edit
  end

  def create
    @mypage = Mypage.new(mypage_params)
    @mypage.save
    respond_with(@mypage)
  end

  def update
    @mypage.update(mypage_params)
    respond_with(@mypage)
  end

  def destroy
    @mypage.destroy
    respond_with(@mypage)
  end

  private
    def set_mypage
      @mypage = Mypage.find(params[:id])
    end

    def mypage_params
      params[:mypage]
    end
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/mypages/_form.html.erb
<%= form_for(@mypage) do |f| %>
  <% if @mypage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mypage.errors.count, "error") %> prohibited this mypage from being saved:</h2>

      <ul>
      <% @mypage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mypages/edit.html.erb
<h1>Editing mypage</h1>

<%= render 'form' %>

<%= link_to 'Show', @mypage %> |
<%= link_to 'Back', mypages_path %>

app/views/mypages/index.html.erb
<h1>仕事の状況</h1>
<%= link_to '申請されたリスト', applies_path , method: :get %>
<%= link_to '承認する', approve_apply_path , method: :get %>

app/views/mypages/new.html.erb
<h1>New mypage</h1>

<%= render 'form' %>

<%= link_to 'Back', mypages_path %>

app/views/mypages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mypage_path(@mypage) %> |
<%= link_to 'Back', mypages_path %>